name: Update Blog Posts

on:
  push:
    branches:
      - master  # 또는 워크플로우를 트리거하고 싶은 브랜치 이름
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py

    - name: Pull latest changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin master

    - name: Push changes if there are any
      run: |
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update blog posts"
          git push https://${{ secrets.GH_PAT }}@github.com/gimbabheaven/gbheaven-log.git
        else
          echo "No changes to commit"
        fi
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
